/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard.leads'
import { Route as DashboardKnowledgeRouteImport } from './routes/dashboard.knowledge'
import { Route as DashboardIntegrationsRouteImport } from './routes/dashboard.integrations'
import { Route as DashboardFeedbackRouteImport } from './routes/dashboard.feedback'
import { Route as DashboardChatbotsRouteImport } from './routes/dashboard.chatbots'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardBotIdRouteImport } from './routes/dashboard.bot.$id'
import { Route as ApiPublicWidgetDotjsRouteImport } from './routes/api.public.widget[.]js'
import { Route as ApiPublicChatRouteImport } from './routes/api.public.chat'
import { Route as ApiPublicLogoApiKeyRouteImport } from './routes/api.public.logo.$apiKey'
import { Route as ApiPublicBotApiKeyRouteImport } from './routes/api.public.bot.$apiKey'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKnowledgeRoute = DashboardKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIntegrationsRoute = DashboardIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFeedbackRoute = DashboardFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChatbotsRoute = DashboardChatbotsRouteImport.update({
  id: '/chatbots',
  path: '/chatbots',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBotIdRoute = DashboardBotIdRouteImport.update({
  id: '/bot/$id',
  path: '/bot/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicWidgetDotjsRoute = ApiPublicWidgetDotjsRouteImport.update({
  id: '/api/public/widget.js',
  path: '/api/public/widget.js',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatRoute = ApiPublicChatRouteImport.update({
  id: '/api/public/chat',
  path: '/api/public/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLogoApiKeyRoute = ApiPublicLogoApiKeyRouteImport.update({
  id: '/api/public/logo/$apiKey',
  path: '/api/public/logo/$apiKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotApiKeyRoute = ApiPublicBotApiKeyRouteImport.update({
  id: '/api/public/bot/$apiKey',
  path: '/api/public/bot/$apiKey',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/chatbots': typeof DashboardChatbotsRoute
  '/dashboard/feedback': typeof DashboardFeedbackRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/knowledge': typeof DashboardKnowledgeRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/widget.js': typeof ApiPublicWidgetDotjsRoute
  '/dashboard/bot/$id': typeof DashboardBotIdRoute
  '/api/public/bot/$apiKey': typeof ApiPublicBotApiKeyRoute
  '/api/public/logo/$apiKey': typeof ApiPublicLogoApiKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/chatbots': typeof DashboardChatbotsRoute
  '/dashboard/feedback': typeof DashboardFeedbackRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/knowledge': typeof DashboardKnowledgeRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/widget.js': typeof ApiPublicWidgetDotjsRoute
  '/dashboard/bot/$id': typeof DashboardBotIdRoute
  '/api/public/bot/$apiKey': typeof ApiPublicBotApiKeyRoute
  '/api/public/logo/$apiKey': typeof ApiPublicLogoApiKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/chatbots': typeof DashboardChatbotsRoute
  '/dashboard/feedback': typeof DashboardFeedbackRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/knowledge': typeof DashboardKnowledgeRoute
  '/dashboard/leads': typeof DashboardLeadsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/widget.js': typeof ApiPublicWidgetDotjsRoute
  '/dashboard/bot/$id': typeof DashboardBotIdRoute
  '/api/public/bot/$apiKey': typeof ApiPublicBotApiKeyRoute
  '/api/public/logo/$apiKey': typeof ApiPublicLogoApiKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/chatbots'
    | '/dashboard/feedback'
    | '/dashboard/integrations'
    | '/dashboard/knowledge'
    | '/dashboard/leads'
    | '/dashboard/notifications'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/public/chat'
    | '/api/public/widget.js'
    | '/dashboard/bot/$id'
    | '/api/public/bot/$apiKey'
    | '/api/public/logo/$apiKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/chatbots'
    | '/dashboard/feedback'
    | '/dashboard/integrations'
    | '/dashboard/knowledge'
    | '/dashboard/leads'
    | '/dashboard/notifications'
    | '/dashboard/settings'
    | '/dashboard'
    | '/api/public/chat'
    | '/api/public/widget.js'
    | '/dashboard/bot/$id'
    | '/api/public/bot/$apiKey'
    | '/api/public/logo/$apiKey'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/chatbots'
    | '/dashboard/feedback'
    | '/dashboard/integrations'
    | '/dashboard/knowledge'
    | '/dashboard/leads'
    | '/dashboard/notifications'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/public/chat'
    | '/api/public/widget.js'
    | '/dashboard/bot/$id'
    | '/api/public/bot/$apiKey'
    | '/api/public/logo/$apiKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ApiPublicChatRoute: typeof ApiPublicChatRoute
  ApiPublicWidgetDotjsRoute: typeof ApiPublicWidgetDotjsRoute
  ApiPublicBotApiKeyRoute: typeof ApiPublicBotApiKeyRoute
  ApiPublicLogoApiKeyRoute: typeof ApiPublicLogoApiKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/knowledge': {
      id: '/dashboard/knowledge'
      path: '/knowledge'
      fullPath: '/dashboard/knowledge'
      preLoaderRoute: typeof DashboardKnowledgeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/integrations': {
      id: '/dashboard/integrations'
      path: '/integrations'
      fullPath: '/dashboard/integrations'
      preLoaderRoute: typeof DashboardIntegrationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/feedback': {
      id: '/dashboard/feedback'
      path: '/feedback'
      fullPath: '/dashboard/feedback'
      preLoaderRoute: typeof DashboardFeedbackRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/chatbots': {
      id: '/dashboard/chatbots'
      path: '/chatbots'
      fullPath: '/dashboard/chatbots'
      preLoaderRoute: typeof DashboardChatbotsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bot/$id': {
      id: '/dashboard/bot/$id'
      path: '/bot/$id'
      fullPath: '/dashboard/bot/$id'
      preLoaderRoute: typeof DashboardBotIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/widget.js': {
      id: '/api/public/widget.js'
      path: '/api/public/widget.js'
      fullPath: '/api/public/widget.js'
      preLoaderRoute: typeof ApiPublicWidgetDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat': {
      id: '/api/public/chat'
      path: '/api/public/chat'
      fullPath: '/api/public/chat'
      preLoaderRoute: typeof ApiPublicChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/logo/$apiKey': {
      id: '/api/public/logo/$apiKey'
      path: '/api/public/logo/$apiKey'
      fullPath: '/api/public/logo/$apiKey'
      preLoaderRoute: typeof ApiPublicLogoApiKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/$apiKey': {
      id: '/api/public/bot/$apiKey'
      path: '/api/public/bot/$apiKey'
      fullPath: '/api/public/bot/$apiKey'
      preLoaderRoute: typeof ApiPublicBotApiKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardChatbotsRoute: typeof DashboardChatbotsRoute
  DashboardFeedbackRoute: typeof DashboardFeedbackRoute
  DashboardIntegrationsRoute: typeof DashboardIntegrationsRoute
  DashboardKnowledgeRoute: typeof DashboardKnowledgeRoute
  DashboardLeadsRoute: typeof DashboardLeadsRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBotIdRoute: typeof DashboardBotIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardChatbotsRoute: DashboardChatbotsRoute,
  DashboardFeedbackRoute: DashboardFeedbackRoute,
  DashboardIntegrationsRoute: DashboardIntegrationsRoute,
  DashboardKnowledgeRoute: DashboardKnowledgeRoute,
  DashboardLeadsRoute: DashboardLeadsRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBotIdRoute: DashboardBotIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ApiPublicChatRoute: ApiPublicChatRoute,
  ApiPublicWidgetDotjsRoute: ApiPublicWidgetDotjsRoute,
  ApiPublicBotApiKeyRoute: ApiPublicBotApiKeyRoute,
  ApiPublicLogoApiKeyRoute: ApiPublicLogoApiKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
